Main: Main.java
	javac -d . Main.java Arctan.java Cosinus.java Dodawanie.java Dzielenie.java Logarytmowanie.java Maksimum.java Minimum.java Mnozenie.java Modulo.java Odejmowanie.java Odwrotnosc.java Operator1Arg.java Operator2Arg.java Potegowanie.java Przeciwienstwo.java Sinus.java Stala.java WartBezwzgl.java Wyrazenie.java Zmienna.java Zbior.java Para.java package-info.java

